name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        
    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew
        
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Run tests
      run: ./gradlew test
      
    - name: Generate Javadoc
      run: ./gradlew javadoc
      
    - name: Upload main artifact
      uses: actions/upload-artifact@v4
      with:
        name: pmweatherapi
        path: build/libs/*[!-javadoc][!-sources].jar
        
    - name: Upload sources
      uses: actions/upload-artifact@v4
      with:
        name: pmweatherapi-sources
        path: build/libs/*-sources.jar
        
    - name: Upload Javadoc
      uses: actions/upload-artifact@v4
      with:
        name: pmweatherapi-javadoc
        path: build/libs/*-javadoc.jar
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          build/reports/tests/
          build/test-results/ 