name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        
    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew
        
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Run tests
      run: ./gradlew test
      
    - name: Generate Javadoc
      run: ./gradlew javadoc
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: build/libs
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: |
          build/reports/tests/
          build/test-results/
          
    - name: Upload Javadoc
      uses: actions/upload-artifact@v4
      with:
        name: Javadoc
        path: build/docs/javadoc/ 